# Generated by Django 6.0 on 2026-03-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantmodel",
            name="calendar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="room_calendar_app.roomcalendarmodel",
            ),
        ),
    ]
