"""
Django settings for a ppm_app project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

HOST_URL = config("HOST_URL", default=":8000")
URL_BASE = config("URL_BASE", default="www.")

ALLOWED_HOSTS = [
    ".localhost",
    "127.0.0.1",
    "[::1]",
    "0.0.0.0",
    "192.168.x.x",
    "1.1.1.1",
    "8080",
    URL_BASE + "." + HOST_URL,
]

CSRF_TRUSTED_ORIGINS = [
    "https://www." + HOST_URL,
    "https://" + URL_BASE + "." + HOST_URL,
]

# Application definition

INSTALLED_APPS = [
    # default
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",  # whitenoise
    "django.contrib.staticfiles",
    # dj extras
    "django.contrib.admindocs",
    "django.contrib.postgres",
    # third party
    "django_bootstrap5",
    "django_htmx",
    "django_browser_reload",
    "allauth",
    "allauth.account",
    # mine
    "accounts.apps.AccountsConfig",
    "base.apps.BaseConfig",
    "session_client.apps.SessionClientConfig",
    "room_calendar_app.apps.RoomCalendarAppConfig",
    "my_numbers.apps.MyNumbersConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # white noise
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",  # django-htmx middleware
    "django_browser_reload.middleware.BrowserReloadMiddleware",  # django reload (browser experience)
    "django.contrib.admindocs.middleware.XViewMiddleware",  # django documentation view link
    "allauth.account.middleware.AccountMiddleware",  # allauth
]

ROOT_URLCONF = "ppm_app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "ppm_app/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ppm_app.wsgi.application"

AUTH_USER_MODEL = "accounts.CustomUser"
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
STATIC_ROOT = (
        BASE_DIR / "assets/"  # change when knowing the real address, plus change url patterns
)
STATICFILES_DIRS = [BASE_DIR / "ppm_app/staticfiles"]

# media
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "ppm_app/uploads"

# admin url
ADMIN_URL = config("ADMIN_URL", default="admin/")

ROOT_URLCONF = "ppm_app.urls"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

# login
LOGIN_REDIRECT_URL = "session_client:client_list"
LOGOUT_REDIRECT_URL = "base:index"

DATE_FORMAT = "%d/%m/%Y"

DATE_INPUT_FORMATS = [
    "%d/%m/%Y",  # '25/10/2006'
    "%Y-%m-%d",  # '2006-10-25'
    "%m/%d/%Y",  # '10/25/2006'
    "%m/%d/%y",  # '10/25/06'
    "%b %d %Y",  # 'Oct 25 2006'
    "%b %d, %Y",  # 'Oct 25, 2006'
    "%d %b %Y",  # '25 Oct 2006'
    "%d %b, %Y",  # '25 Oct, 2006'
    "%B %d %Y",  # 'October 25 2006'
    "%B %d, %Y",  # 'October 25, 2006'
    "%d %B %Y",  # '25 October 2006'
    "%d %B, %Y",  # '25 October, 2006'
]

LANGUAGES = [
    ("es", _("Spanish")),
    ("en", _("English")),
]

LOCALE_PATHS = [
    BASE_DIR / "ppm_app/locale",
]

# logging conf to add some info when things are wrong (there are more complex setups).
# By default django messages are shown when debug True even in info level.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG" if DEBUG else "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}

INTERNAL_IPS = ("127.0.0.1",)

LOGIN_REDIRECT_URL = "base:index"
LOGOUT_REDIRECT_URL = "base:index"
LOGIN_URL = "account_login"
AUTHENTICATION_LOGOUT_REDIRECT = "base:index"
AUTH_USER_MODEL = "accounts.CustomUser"
ACCOUNT_LOGIN_BY_CODE_ENABLED = True

MFA_TOTP_ISSUER = "Dreamy-admin"

MFA_SUPPORTED_TYPES = ["totp", "webauthn", "recovery_codes"]
MFA_PASSKEY_LOGIN_ENABLED = True

# * Django All auth config
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

ACCOUNT_SIGNUP_FORM_HONEYPOT_FIELD = "phone_number"

ACCOUNT_FORMS = {
    "signup": "accounts.forms.MyCustomSignupForm",
    "login": "accounts.forms.MyCustomLoginForm",
}

ACCOUNT_EMAIL_UNKNOWN_ACCOUNTS = False

SILENCED_SYSTEM_CHECKS = [
    "fields.W161",
]
