# Generated by Django 5.0.6 on 2024-06-11 19:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_code", models.CharField(default="", max_length=10)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("Pvt", "Private"),
                            ("Srv", "Service"),
                            ("EAP", "EAP"),
                            ("Sp", "Supervisee"),
                            ("Other", "Other"),
                        ],
                        default="Pvt",
                        max_length=20,
                    ),
                ),
                (
                    "fee",
                    models.IntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("motive", models.CharField(default="", max_length=200)),
                ("rel", models.TextField(default="")),
                ("goal", models.TextField(default="")),
                ("strategy", models.TextField(default="")),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(default="Session", max_length=200)),
                ("notes", models.TextField(default="")),
                ("paid", models.BooleanField(default=False)),
                (
                    "attended",
                    models.CharField(
                        choices=[
                            ("Att", "Attended"),
                            ("LC", "Late Cancelled"),
                            ("Mssd", "Missed"),
                            ("Cll", "Cancelled"),
                        ],
                        default="attended",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tools.client"
                    ),
                ),
            ],
        ),
    ]
