# Generated by Django 5.0.6 on 2024-11-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0002_session_user_alter_session_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="nick_name",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
    ]
