# Generated by Django 5.0.6 on 2024-11-23 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0003_client_nick_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="client_code",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="client",
            old_name="client_type",
            new_name="type",
        ),
    ]
