# Generated by Django 5.0.6 on 2024-11-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0004_rename_client_code_client_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="amount_paid",
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
