# Generated by Django 5.0.6 on 2024-11-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0005_session_amount_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="amount_paid",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
