providers = ["...", "python"]

[phases.setup]
nixPkgs = ["...", "uv"] # Install the ffmpeg package from Nix

[variables]
UV_PYTHON_DOWNLOADS = 'automatic'
UV_LINK_MODE = 'copy'
NIXPACKS_PYTHON_PACKAGE_MANAGER = 'uv'

[start]
cmd = "uv run manage.py collectstatic --noinput && manage.py migrate && gunicorn ppm_app.wsgi"