providers = ["...", "python"]


[phases.setup]
nixPkgs = ["python3", "postgresql_17.dev", "gcc"]
nixLibs = ["zlib", "stdenv.cc.cc.lib"]
aptPkgs = ["curl", "wget"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install uv==0.5.11",
  ". /opt/venv/bin/activate && uv sync --no-dev --frozen"
]
paths = ["/opt/venv/bin"]


[phases.build]
....

[start]
cmd = "uv run manage.py collectstatic --noinput && manage.py migrate && gunicorn ppm_app.wsgi"


[variables]
NIXPACKS_PYTHON_PACKAGE_MANAGER = 'uv'
UV_PYTHON_DOWNLOADS = 'never'
UV_LINK_MODE = 'copy'
UV_PYTHON = "/opt/venv/bin/python"
NIXPACKS_UV_VERSION = "0.1.0"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONFAULTHANDLER = "1"
PYTHONHASHSEED = "random"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PIP_DEFAULT_TIMEOUT = "100"
UV_PROJECT_ENVIRONMENT = "/opt/venv"
