import polib
import os

translations = {
    "Log into your account": "Inicie sesión en su cuenta",
    "Log in": "Iniciar sesión",
    "Register an account": "Registrar una cuenta",
    "Register": "Registrarse",
    "Ups": "Ups",
    "This page does not exist": "Esta página no existe",
    "Toggle theme": "Cambiar tema",
    "Dawn": "Amanecer",
    "Dusk": "Atardecer",
    "Hello": "Hola",
    "Logout": "Cerrar sesión",
    "Login": "Iniciar sesión",
    "Home": "Inicio",
    "Week View": "Vista semanal",
    "Close": "Cerrar",
    "Toggle Dropdown": "Alternar menú desplegable",
    "Code": "Código",
    "Type": "Tipo",
    "Fee": "Tarifa",
    "Tenant": "Inquilino",
    "Default Day": "Día predeterminado",
    "Duration": "Duración",
    "Active": "Activo",
    "Link": "Enlace",
    "time": "hora",
    "Keywords": "Palabras clave",
    "Date": "Fecha",
    "Client": "Cliente",
    "Paid": "Pagado",
    "Amount": "Monto",
    "Open": "Abierto",
    "Attendance": "Asistencia",
    "Day and Time": "Día y Hora",
    "Add an Identifier code": "Agregar un código identificador",
    "Select a type of client": "Seleccionar un tipo de cliente",
    "Whats your agreed fee": "¿Cuál es su tarifa acordada?",
    "Move from archive to active or vice versa": "Mover de archivado a activo o viceversa",
    "Default day of week": "Día predeterminado de la semana",
    "default time": "hora predeterminada",
    "default duration": "duración predeterminada",
    "External link": "Enlace externo",
    "Link to a client": "Enlace a un cliente",
    "Date of session": "Fecha de la sesión",
    "Start of session?": "¿Inicio de la sesión?",
    "End of session": "Fin de la sesión",
    "words for search": "palabras para buscar",
    "Archive": "Archivar",
    "Save": "Guardar",
    "Add Session": "Agregar Sesión",
    "Delete": "Eliminar",
    "Notes": "Notas",
    "Send": "Enviar",
    "Client Link": "Enlace del Cliente",
    "Day": "Día",
    "Time": "Hora",
    "Series": "Serie",
    "keywords": "palabras clave",
    "Status": "Estado",
    "Payment": "Pago",
    "archived": "archivado",
    "There are no clients yet.": "Aún no hay clientes.",
    "Filter clients": "Filtrar clientes",
    "Time from creation": "Tiempo desde la creación",
    "Open Sessions": "Sesiones Abiertas",
    "Date default": "Fecha predeterminada",
    "Client tenant": "Inquilino cliente",
    "sessions paid": "sesiones pagadas",
    "paiment expected": "pago esperado",
    "Attendance percentage": "Porcentaje de asistencia",
    "Future sessions": "Sesiones futuras",
    "book 3 forward": "reservar 3 adelante",
    "book 6 forward": "reservar 6 adelante",
    "Search in Sessions Keywords, Nick Name, and Room": "Buscar en palabras clave de sesiones, apodo y habitación",
    "Loading": "Cargando",
    "Ups! Session overlaps": "¡Ups! La sesión se superpone",
    "Created Sessions": "Sesiones Creadas",
    "Overlapping Sessions": "Sesiones Superpuestas",
    "Clients": "Clientes",
    "Current": "Actual",
    "Search": "Buscar",
    "Review": "Revisar",
    "Archived": "Archivado",
    "Sessions": "Sesiones",
    "ups, overlaps": "ups, se superpone",
    "Saved ok": "Guardado correctamente",
    "Name": "Nombre",
    "Description": "Descripción",
    "Percentage charge": "Cargo por porcentaje",
    "Cost of per session": "Costo por sesión",
    "Your name to display": "Su nombre a mostrar",
    "Name for your records": "Nombre para sus registros",
    "a description of the place you are linking to": "una descripción del lugar al que se está vinculando",
    "Agreement type": "Tipo de acuerdo",
    "Select a linked tenant": "Seleccionar un inquilino vinculado",
    "Monthly cost for this block": "Costo mensual para este bloque",
    "Period": "Período",
    "Income": "Ingresos",
    "There are no Spaces yet.": "Aún no hay espacios.",
    "Filter Rooms": "Filtrar habitaciones",
    "Agreement": "Acuerdo",
    "Rent": "Alquiler",
    "Total": "Total",
    "Add a new Room.": "Agregar una nueva habitación.",
    "Total Sessions": "Total de Sesiones",
    "Expected pay": "Pago esperado",
    "Pay": "Pago",
    "Display": "Mostrar",
    "Tenancies": "Arrendamientos",
    "Share Code": "Compartir código",
    "Blocks View": "Vista de bloques",
    "Week View Clients": "Vista semanal de clientes",
    "Edit Block": "Editar bloque",
    "Add a new Block": "Agregar un nuevo bloque",
    "Submit": "Enviar",
    "Add Client": "Agregar cliente",
    "Edit": "Editar",
    "Add new": "Agregar nuevo",
    "Room": "Habitación",
    "Add a form of pay": "Agregar una forma de pago",
    "Add": "Agregar",
    "Calendar": "Calendario",
    "Week": "Semana",
    "Blocks": "Bloques",
    "Rooms": "Habitaciones",
    "Spaces": "Espacios",
    "Rentals": "Alquileres",
    "Manage": "Gestionar",
    "Report": "Informe",
    "Admin for therapists": "Administración para terapeutas",
    "Therapists handle a lot of complexity": "Los terapeutas manejan mucha complejidad",
    "Let's make it a bit easier to handle their admin": "Hagámoslo un poco más fácil de manejar su administración",
    "admin": "admin",
}

po_files = [
    "./session_client/locale/es/LC_MESSAGES/django.po",
    "./ppm_app/locale/es/LC_MESSAGES/django.po",
    "./base/locale/es/LC_MESSAGES/django.po",
    "./room_calendar_app/locale/es/LC_MESSAGES/django.po",
]

for po_file_path in po_files:
    if os.path.exists(po_file_path):
        po = polib.pofile(po_file_path)
        updated = False
        for entry in po:
            if not entry.msgstr and entry.msgid in translations:
                entry.msgstr = translations[entry.msgid]
                if 'fuzzy' in entry.flags:
                    entry.flags.remove('fuzzy')
                updated = True
        if updated:
            po.save()
            print(f"Updated {po_file_path}")
        else:
            print(f"No updates for {po_file_path}")
    else:
        print(f"File not found: {po_file_path}")
