# Generated by Django 5.2.1 on 2025-05-21 14:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("room_calendar_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(help_text="Add an Identifier code", max_length=10),
                ),
                (
                    "nick_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Give it a memorable nickname",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Pvt", "Private"),
                            ("Srv", "Service"),
                            ("EAP", "EAP"),
                            ("Sp", "Supervisee"),
                            ("Adm", "Other-Admin"),
                            ("Prss", "Other-Processing"),
                            ("CPD", "Other-CPD"),
                            ("Other", "Other"),
                        ],
                        default="Pvt",
                        help_text="Select a type of client",
                        max_length=20,
                    ),
                ),
                (
                    "fee",
                    models.IntegerField(
                        default=50,
                        help_text="Whats your agreed fee",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Change if your client is active or archived",
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (7, "Sun"),
                            (1, "Mon"),
                            (2, "Tue"),
                            (3, "Wed"),
                            (4, "Thu"),
                            (5, "Fri"),
                            (6, "Sat"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        choices=[
                            ("0:30:00", "0:30:00"),
                            ("1:00:00", "1:00:00"),
                            ("1:30:00", "1:30:00"),
                            ("2:00:00", "2:00:00"),
                            ("3:00:00", "3:00:00"),
                            ("4:00:00", "4:00:00"),
                        ],
                        default="60 minutes",
                    ),
                ),
                (
                    "room_calendar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="room_calendar_app.roomcalendarmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ("code", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="SessionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True, help_text="Start of session?", null=True
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True, help_text="End of session", null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Give the session a title",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Longer note of Session"
                    ),
                ),
                ("paid", models.BooleanField(blank=True, default=False)),
                (
                    "attended",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Att", "Attended"),
                            ("LateC", "Late Cancelled"),
                            ("Missed", "Missed"),
                            ("Cancel", "Cancelled"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("amount_paid", models.IntegerField(blank=True, default=0)),
                ("open", models.BooleanField(blank=True, default=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="room_calendar_app.roomcalendarmodel",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Link to a client",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="session_client.clientmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "ordering": ("start_datetime",),
                "base_manager_name": "objects",
            },
        ),
    ]
