# Generated by Django 6.0a1 on 2025-12-20 11:59

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from pendulum import Time


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("room_calendar_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(help_text="Add an Identifier code", max_length=15),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Private", "Private"),
                            ("RoomP", "Room Percentage"),
                            ("Agency", "Agency"),
                            ("EAP", "EAP"),
                            ("SuperV", "Supervisee"),
                            ("Other", "Other"),
                        ],
                        default="Pvt",
                        help_text="Select a type of client",
                        max_length=20,
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=60,
                        help_text="Whats your agreed fee",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Move from archive to active or vice versa",
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Mon"),
                            (1, "Tue"),
                            (2, "Wed"),
                            (3, "Thu"),
                            (4, "Fri"),
                            (5, "Sat"),
                            (6, "Sun"),
                        ],
                        default=1,
                        help_text="Default day of week",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        choices=[
                            (Time(8, 0, 0), "08:00 AM"),
                            (Time(8, 30, 0), "08:30 AM"),
                            (Time(9, 0, 0), "09:00 AM"),
                            (Time(9, 30, 0), "09:30 AM"),
                            (Time(10, 0, 0), "10:00 AM"),
                            (Time(10, 30, 0), "10:30 AM"),
                            (Time(11, 0, 0), "11:00 AM"),
                            (Time(11, 30, 0), "11:30 AM"),
                            (Time(12, 0, 0), "12:00 PM"),
                            (Time(12, 30, 0), "12:30 PM"),
                            (Time(13, 0, 0), "01:00 PM"),
                            (Time(13, 30, 0), "01:30 PM"),
                            (Time(14, 0, 0), "02:00 PM"),
                            (Time(14, 30, 0), "02:30 PM"),
                            (Time(15, 0, 0), "03:00 PM"),
                            (Time(15, 30, 0), "03:30 PM"),
                            (Time(16, 0, 0), "04:00 PM"),
                            (Time(16, 30, 0), "04:30 PM"),
                            (Time(17, 0, 0), "05:00 PM"),
                            (Time(17, 30, 0), "05:30 PM"),
                            (Time(18, 0, 0), "06:00 PM"),
                            (Time(18, 30, 0), "06:30 PM"),
                            (Time(19, 0, 0), "07:00 PM"),
                            (Time(19, 30, 0), "07:30 PM"),
                            (Time(20, 0, 0), "08:00 PM"),
                            (Time(20, 30, 0), "08:30 PM"),
                            (Time(21, 0, 0), "09:00 PM"),
                            (Time(21, 30, 0), "09:30 PM"),
                            (Time(22, 0, 0), "10:00 PM"),
                        ],
                        help_text="default time",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        choices=[
                            (datetime.timedelta(seconds=1800), "0:30:00"),
                            (datetime.timedelta(seconds=3600), "1:00:00"),
                            (datetime.timedelta(seconds=5400), "1:30:00"),
                            (datetime.timedelta(seconds=7200), "2:00:00"),
                            (datetime.timedelta(seconds=10800), "3:00:00"),
                        ],
                        default="60 minutes",
                        help_text="default duration",
                    ),
                ),
                (
                    "series",
                    models.IntegerField(
                        choices=[(1, "Every week"), (2, "Every two weeks")], default=1
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, help_text="External link", null=True),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="room_calendar_app.tenantmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ("code", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="SessionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date",
                    models.DateField(
                        blank=True, default="2025-10-3", help_text="Date of session"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(default="09:00:00", help_text="Start of session?"),
                ),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, default="10:00:00", help_text="End of session"
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, help_text="words for search", max_length=25
                    ),
                ),
                ("paid", models.BooleanField(blank=True, default=False)),
                (
                    "attendance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Attended", "Attended"),
                            ("LateC", "Late Cancel"),
                            ("Missed", "Missed"),
                            ("Cancel", "Cancelled"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=60.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("open", models.BooleanField(blank=True, default=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="room_calendar_app.roomcalendarmodel",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Link to a client",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="session_client.clientmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "ordering": ("date", "start_time"),
                "get_latest_by": "date",
                "base_manager_name": "objects",
            },
        ),
    ]
