# Generated by Django 5.2.1 on 2025-06-10 11:08

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from pendulum import Time

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("room_calendar_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(help_text="Add an Identifier code", max_length=10),
                ),
                (
                    "nick_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Give it a memorable nickname",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Pvt", "Private"),
                            ("Srv", "Agency"),
                            ("EAP", "EAP"),
                            ("Sp", "Supervisee"),
                            ("Other", "Other"),
                        ],
                        default="Pvt",
                        help_text="Select a type of client",
                        max_length=20,
                    ),
                ),
                (
                    "fee",
                    models.IntegerField(
                        default=50,
                        help_text="Whats your agreed fee",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Change if your client is active or archived",
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (7, "Sun"),
                            (1, "Mon"),
                            (2, "Tue"),
                            (3, "Wed"),
                            (4, "Thu"),
                            (5, "Fri"),
                            (6, "Sat"),
                        ],
                        default=1,
                        help_text="Default day of week",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        choices=[
                            (Time(8, 0, 0), "08:00 AM"),
                            (Time(8, 30, 0), "08:30 AM"),
                            (Time(9, 0, 0), "09:00 AM"),
                            (Time(9, 30, 0), "09:30 AM"),
                            (Time(10, 0, 0), "10:00 AM"),
                            (Time(10, 30, 0), "10:30 AM"),
                            (Time(11, 0, 0), "11:00 AM"),
                            (Time(11, 30, 0), "11:30 AM"),
                            (Time(12, 0, 0), "12:00 PM"),
                            (Time(12, 30, 0), "12:30 PM"),
                            (Time(13, 0, 0), "01:00 PM"),
                            (Time(13, 30, 0), "01:30 PM"),
                            (Time(14, 0, 0), "02:00 PM"),
                            (Time(14, 30, 0), "02:30 PM"),
                            (Time(15, 0, 0), "03:00 PM"),
                            (Time(15, 30, 0), "03:30 PM"),
                            (Time(16, 0, 0), "04:00 PM"),
                            (Time(16, 30, 0), "04:30 PM"),
                            (Time(17, 0, 0), "05:00 PM"),
                            (Time(17, 30, 0), "05:30 PM"),
                            (Time(18, 0, 0), "06:00 PM"),
                            (Time(18, 30, 0), "06:30 PM"),
                            (Time(19, 0, 0), "07:00 PM"),
                            (Time(19, 30, 0), "07:30 PM"),
                            (Time(20, 0, 0), "08:00 PM"),
                            (Time(20, 30, 0), "08:30 PM"),
                            (Time(21, 0, 0), "09:00 PM"),
                            (Time(21, 30, 0), "09:30 PM"),
                            (Time(22, 0, 0), "10:00 PM"),
                        ],
                        help_text="default time",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        choices=[
                            (datetime.timedelta(seconds=1800), "0:30:00"),
                            (datetime.timedelta(seconds=3600), "1:00:00"),
                            (datetime.timedelta(seconds=5400), "1:30:00"),
                            (datetime.timedelta(seconds=7200), "2:00:00"),
                            (datetime.timedelta(seconds=10800), "3:00:00"),
                            (datetime.timedelta(seconds=14400), "4:00:00"),
                        ],
                        default="60 minutes",
                        help_text="default duration",
                    ),
                ),
                (
                    "room_calendar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="room_calendar_app.roomcalendarmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ("code", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="SessionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True, help_text="Start of session?", null=True
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True, help_text="End of session", null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Give the session a title",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Longer note of Session"
                    ),
                ),
                ("paid", models.BooleanField(blank=True, default=False)),
                (
                    "attended",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Att", "Attended"),
                            ("LateC", "Late Cancelled"),
                            ("Missed", "Missed"),
                            ("Cancel", "Cancelled"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("amount_paid", models.IntegerField(blank=True, default=0)),
                ("open", models.BooleanField(blank=True, default=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="room_calendar_app.roomcalendarmodel",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Link to a client",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="session_client.clientmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "ordering": ("start_datetime",),
                "base_manager_name": "objects",
            },
        ),
    ]
