# Generated by Django 6.0 on 2026-02-03 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0001_initial"),
        ("session_client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmodel",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="room_calendar_app.tenantmodel",
            ),
        ),
    ]
