# Generated by Django 6.0a1 on 2025-11-27 15:01

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmodel",
            name="brief",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True,
                default="",
                help_text="250 characters note",
                max_length=250,
                null=True,
            ),
        ),
    ]
