# Generated by Django 6.0a1 on 2025-10-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmodel",
            name="attendance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Attended", "Attended"),
                    ("LateC", "Late Cancel"),
                    ("Missed", "Missed"),
                    ("Cancel", "Cancelled"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
