# Generated by Django 5.2.1 on 2025-05-21 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionmodel",
            name="user",
        ),
    ]
