# Generated by Django 5.2.1 on 2025-08-05 08:11

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0002_remove_sessionmodel_user"),
    ]

    operations = [
        VectorExtension()
    ]
