# Generated by Django 6.0a1 on 2025-12-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0002_alter_sessionmodel_brief"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientmodel",
            name="nick_name",
        ),
        migrations.RemoveField(
            model_name="sessionmodel",
            name="brief",
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="code",
            field=models.CharField(help_text="Add an Identifier code", max_length=15),
        ),
    ]
