# Generated by Django 6.0a1 on 2025-11-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0002_alter_sessionmodel_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="day",
            field=models.IntegerField(
                choices=[
                    (6, "Sun"),
                    (0, "Mon"),
                    (1, "Tue"),
                    (2, "Wed"),
                    (3, "Thu"),
                    (4, "Fri"),
                    (5, "Sat"),
                ],
                default=1,
                help_text="Default day of week",
            ),
        ),
    ]
