# Generated by Django 5.2.1 on 2025-08-05 08:11

from django.db import migrations
from django.db.migrations.operations.base import Operation

class VectorExtension(Operation):
    reduces_to_sql = True
    reversible = True
    hints = {}  # Important for Django’s migrate executor compatibility

    def __init__(self, name="vector", schema=None):
        self.name = name
        self.schema = schema

    def state_forwards(self, app_label, state):
        pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        ext = schema_editor.quote_name(self.name)
        if self.schema:
            schema = schema_editor.quote_name(self.schema)
            schema_editor.execute(f"CREATE SCHEMA IF NOT EXISTS {schema}")
            schema_qual = f"{schema}.{ext}"
        else:
            schema_qual = ext
        schema_editor.execute(f"CREATE EXTENSION IF NOT EXISTS {ext}")

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        ext = schema_editor.quote_name(self.name)
        schema_editor.execute(f"DROP EXTENSION IF EXISTS {ext}")

    def describe(self):
        return f"Creates PostgreSQL extension {self.name}"


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0002_remove_sessionmodel_user"),
    ]

    operations = [
        VectorExtension()
    ]
