# Generated by Django 6.0 on 2026-02-03 21:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0002_sessionmodel_tenant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionmodel",
            name="calendar",
        ),
    ]
