# Generated by Django 5.2.1 on 2025-05-23 17:13

import datetime
import session_client.choices
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0003_sessionmodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmodel",
            name="time",
            field=models.TimeField(
                blank=True,
                choices=session_client.choices.time_slot_options,
                default="08:00",
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="duration",
            field=models.DurationField(
                choices=[
                    (datetime.timedelta(seconds=1800), "0:30:00"),
                    (datetime.timedelta(seconds=3600), "1:00:00"),
                    (datetime.timedelta(seconds=5400), "1:30:00"),
                    (datetime.timedelta(seconds=7200), "2:00:00"),
                    (datetime.timedelta(seconds=10800), "3:00:00"),
                    (datetime.timedelta(seconds=14400), "4:00:00"),
                ],
                default="60 minutes",
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("Pvt", "Private"),
                    ("Srv", "Agency"),
                    ("EAP", "EAP"),
                    ("Sp", "Supervisee"),
                    ("Other", "Other"),
                ],
                default="Pvt",
                help_text="Select a type of client",
                max_length=20,
            ),
        ),
    ]
