# Generated by Django 6.0a1 on 2025-11-25 10:54

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0003_alter_clientmodel_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionmodel",
            name="keywords",
            field=models.CharField(
                blank=True, help_text="words for search", max_length=25
            ),
        ),
        migrations.AlterField(
            model_name="sessionmodel",
            name="brief",
            field=encrypted_fields.fields.EncryptedCharField(
                blank=True, default="", help_text="250 characters note", max_length=250
            ),
        ),
    ]
