# Generated by Django 5.1.6 on 2025-04-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0003_remove_client_active_remove_client_goal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Change if your client is active or archived"
            ),
        ),
    ]
