# Generated by Django 5.2.1 on 2025-08-05 08:34

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0003_auto_20250805_0811"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionmodel",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="sessionmodel",
            name="title",
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="brief",
            field=models.CharField(
                blank=True, default="", help_text="250 characters note", max_length=250
            ),
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="brief_vector",
            field=pgvector.django.vector.VectorField(dimensions=3, null=True),
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="user",
            field=models.ForeignKey(
                default=0,
                help_text="Link to a user",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sessionmodel",
            name="client",
            field=models.ForeignKey(
                help_text="Link to a client",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="session_client.clientmodel",
            ),
        ),
    ]
