# Generated by Django 6.0a1 on 2025-12-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0003_remove_clientmodel_nick_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmodel",
            name="link",
            field=models.URLField(
                blank=True, help_text="Link to client's external management", null=True
            ),
        ),
    ]
