# Generated by Django 5.2.1 on 2025-09-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "session_client",
            "0004_remove_sessionmodel_notes_remove_sessionmodel_title_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionmodel",
            name="user",
        ),
        migrations.AlterField(
            model_name="sessionmodel",
            name="client",
            field=models.ForeignKey(
                help_text="Link to a client",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="session_client.clientmodel",
            ),
        ),
    ]
