# Generated by Django 5.2.1 on 2025-05-23 17:21

import datetime
import session_client.choices
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0004_clientmodel_time_alter_clientmodel_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="day",
            field=models.IntegerField(
                choices=[
                    (7, "Sun"),
                    (1, "Mon"),
                    (2, "Tue"),
                    (3, "Wed"),
                    (4, "Thu"),
                    (5, "Fri"),
                    (6, "Sat"),
                ],
                default=1,
                help_text="Default day of week",
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="duration",
            field=models.DurationField(
                choices=[
                    (datetime.timedelta(seconds=1800), "0:30:00"),
                    (datetime.timedelta(seconds=3600), "1:00:00"),
                    (datetime.timedelta(seconds=5400), "1:30:00"),
                    (datetime.timedelta(seconds=7200), "2:00:00"),
                    (datetime.timedelta(seconds=10800), "3:00:00"),
                    (datetime.timedelta(seconds=14400), "4:00:00"),
                ],
                default="60 minutes",
                help_text="default duration",
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="time",
            field=models.TimeField(
                blank=True,
                choices=session_client.choices.time_slot_options,
                default="08:00",
                help_text="default time",
            ),
        ),
    ]
