# Generated by Django 6.0 on 2026-02-14 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0001_initial"),
        ("session_client", "0004_alter_sessionmodel_tenant_clientextratimes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClientExtraTimes",
            new_name="ClientTimes",
        ),
    ]
