# Generated by Django 5.1.6 on 2025-04-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0004_client_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
