# Generated by Django 5.2.1 on 2025-05-23 18:23

import session_client.choices
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "session_client",
            "0005_alter_clientmodel_day_alter_clientmodel_duration_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="time",
            field=models.TimeField(
                blank=True,
                choices=session_client.choices.time_slot_options,
                help_text="default time",
            ),
        ),
    ]
