# Generated by Django 5.2.1 on 2025-09-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0005_remove_sessionmodel_user_alter_sessionmodel_client"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sessionmodel",
            options={
                "base_manager_name": "objects",
                "get_latest_by": "start_datetime",
                "ordering": ("start_datetime",),
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
            },
        ),
        migrations.AddField(
            model_name="clientmodel",
            name="series",
            field=models.IntegerField(
                choices=[(1, "Every week"), (2, "Every two weeks")], default=1
            ),
        ),
    ]
