# Generated by Django 6.0 on 2026-02-14 21:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0005_rename_clientextratimes_clienttimes"),
    ]

    operations = [
        migrations.AddField(
            model_name="clienttimes",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clienttimes",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="times",
                to="session_client.clientmodel",
            ),
        ),
    ]
