# Generated by Django 5.2.1 on 2025-09-10 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0006_alter_sessionmodel_options_clientmodel_series"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientmodel",
            old_name="room_calendar",
            new_name="calendar",
        ),
    ]
