# Generated by Django 5.1.6 on 2025-04-05 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0006_session_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="session_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="amount_paid",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="session",
            name="attended",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Att", "Attended"),
                    ("LC", "Late Cancelled"),
                    ("Missed", "Missed"),
                    ("Cll", "Cancelled"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="client",
            field=models.ForeignKey(
                help_text="Link to a client",
                on_delete=django.db.models.deletion.PROTECT,
                to="session_client.client",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="notes",
            field=models.TextField(
                blank=True, default="", help_text="Longer note of Session"
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="open",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="paid",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="session",
            name="title",
            field=models.CharField(
                default="", help_text="Give the session a title", max_length=200
            ),
        ),
    ]
