# Generated by Django 5.2.1 on 2025-05-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0002_remove_event_client"),
        (
            "session_client",
            "0007_session_session_date_alter_session_amount_paid_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ("updated_at", "code")},
        ),
        migrations.AddField(
            model_name="client",
            name="room_calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="room_calendar_app.roomcalendarmodel",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="type",
            field=models.CharField(
                choices=[
                    ("Pvt", "Private"),
                    ("Srv", "Service"),
                    ("EAP", "EAP"),
                    ("Sp", "Supervisee"),
                    ("Adm", "Other-Admin"),
                    ("Prss", "Other-Processing"),
                    ("CPD", "Other-CPD"),
                    ("Other", "Other"),
                ],
                default="Pvt",
                help_text="Select a type of client",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="attended",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Att", "Attended"),
                    ("LateC", "Late Cancelled"),
                    ("Missed", "Missed"),
                    ("Cancel", "Cancelled"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="client",
            field=models.ForeignKey(
                help_text="Link to a client",
                on_delete=django.db.models.deletion.CASCADE,
                to="session_client.client",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="session_date",
            field=models.DateTimeField(
                blank=True, help_text="When was the session?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Give the session a title",
                max_length=200,
            ),
        ),
    ]
