# Generated by Django 6.0 on 2026-03-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "session_client",
            "0007_remove_clientmodel_day_remove_clientmodel_time_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="clienttimes",
            name="fortnight",
            field=models.BooleanField(default=False, help_text="Set as fortnight"),
        ),
    ]
