# Generated by Django 5.2.1 on 2025-09-11 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0007_rename_room_calendar_clientmodel_calendar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sessionmodel",
            options={
                "base_manager_name": "objects",
                "get_latest_by": "date",
                "ordering": ("date", "start_time"),
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
            },
        ),
        migrations.RemoveField(
            model_name="sessionmodel",
            name="end_datetime",
        ),
        migrations.RemoveField(
            model_name="sessionmodel",
            name="start_datetime",
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="date",
            field=models.DateField(blank=True, help_text="Date of session", null=True),
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="end_time",
            field=models.TimeField(blank=True, help_text="End of session", null=True),
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="start_time",
            field=models.TimeField(
                blank=True, help_text="Start of session?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="duration",
            field=models.DurationField(
                choices=[
                    (datetime.timedelta(seconds=1800), "0:30:00"),
                    (datetime.timedelta(seconds=3600), "1:00:00"),
                    (datetime.timedelta(seconds=5400), "1:30:00"),
                    (datetime.timedelta(seconds=7200), "2:00:00"),
                    (datetime.timedelta(seconds=10800), "3:00:00"),
                ],
                default="60 minutes",
                help_text="default duration",
            ),
        ),
    ]
