# Generated by Django 6.0a1 on 2025-10-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0008_alter_sessionmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Move from archive to active or viceversa"
            ),
        ),
        migrations.AlterField(
            model_name="sessionmodel",
            name="start_time",
            field=models.TimeField(default="09:00:00", help_text="Start of session?"),
        ),
    ]
