# Generated by Django 5.2.1 on 2025-05-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0008_alter_client_options_client_room_calendar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="day",
            field=models.IntegerField(
                choices=[
                    (7, "Sun"),
                    (1, "Mon"),
                    (2, "Tue"),
                    (3, "Wed"),
                    (4, "Thu"),
                    (5, "Fri"),
                    (6, "Sat"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="duration",
            field=models.DurationField(
                choices=[
                    ("0:30:00", "0:30:00"),
                    ("1:00:00", "1:00:00"),
                    ("1:30:00", "1:30:00"),
                    ("2:00:00", "2:00:00"),
                    ("3:00:00", "3:00:00"),
                    ("4:00:00", "4:00:00"),
                ],
                default="60 minutes",
            ),
        ),
    ]
