# Generated by Django 6.0a1 on 2025-10-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0009_alter_clientmodel_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmodel",
            name="end_time",
            field=models.TimeField(default="10:00:00", help_text="End of session"),
        ),
    ]
