# Generated by Django 5.2.1 on 2025-05-16 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0002_remove_event_client"),
        ("session_client", "0009_client_day_client_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientmodel",
            options={
                "ordering": ("code", "created_at"),
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.RenameModel(
            old_name="Client",
            new_name="ClientModel",
        ),
        migrations.CreateModel(
            name="SessionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True, help_text="Start of session?", null=True
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True, help_text="End of session", null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Give the session a title",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Longer note of Session"
                    ),
                ),
                ("paid", models.BooleanField(blank=True, default=False)),
                (
                    "attended",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Att", "Attended"),
                            ("LateC", "Late Cancelled"),
                            ("Missed", "Missed"),
                            ("Cancel", "Cancelled"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("amount_paid", models.IntegerField(blank=True, default=0)),
                ("open", models.BooleanField(blank=True, default=True)),
                (
                    "calendar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="room_calendar_app.roomcalendarmodel",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Link to a client",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="session_client.clientmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "ordering": ("start_datetime",),
                "base_manager_name": "objects",
            },
        ),
        migrations.DeleteModel(
            name="Session",
        ),
    ]
