# Generated by Django 6.0a1 on 2025-10-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0010_alter_sessionmodel_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmodel",
            name="end_time",
            field=models.TimeField(blank=True, help_text="End of session", null=True),
        ),
    ]
