# Generated by Django 6.0.3 on 2026-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0011_alter_clientmodel_duration_alter_sessionmodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="duration",
            field=models.DurationField(
                choices=[
                    ("00:30:00", "30 min"),
                    ("01:00:00", "1 h"),
                    ("01:30:00", "1.5 h"),
                    ("02:00:00", "2 h"),
                    ("03:00:00", "3 h"),
                ],
                default="60 minutes",
                help_text="default duration",
            ),
        ),
    ]
