# Generated by Django 6.0a1 on 2025-10-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0011_alter_sessionmodel_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmodel",
            name="date",
            field=models.DateField(
                blank=True, default="2025-10-3", help_text="Date of session"
            ),
        ),
        migrations.AlterField(
            model_name="sessionmodel",
            name="end_time",
            field=models.TimeField(
                blank=True, default="10:00:00", help_text="End of session"
            ),
        ),
    ]
