# Generated by Django 6.0a1 on 2025-10-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0012_alter_sessionmodel_date_alter_sessionmodel_end_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionmodel",
            name="attended",
        ),
        migrations.AddField(
            model_name="sessionmodel",
            name="attendance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Attended", "Attended"),
                    ("LateC", "Late Cancelled"),
                    ("Missed", "Missed"),
                    ("Cancel", "Cancelled"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
