# Generated by Django 6.0a1 on 2025-10-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0013_remove_sessionmodel_attended_sessionmodel_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Move from archive to active or vice versa"
            ),
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="type",
            field=models.CharField(
                choices=[
                    ("Private", "Private"),
                    ("RoomL", "Room-Linked"),
                    ("Agency", "Agency"),
                    ("EAP", "EAP"),
                    ("SuperV", "Supervisee"),
                    ("Other", "Other"),
                ],
                default="Pvt",
                help_text="Select a type of client",
                max_length=20,
            ),
        ),
    ]
