# Generated by Django 6.0.3 on 2026-05-04 14:30

import datetime
from django.db import migrations, models
from pendulum import Duration


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0013_alter_clientmodel_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="duration",
            field=models.DurationField(
                choices=[
                    (datetime.timedelta(seconds=1800), Duration(minutes=30)),
                    (datetime.timedelta(seconds=3600), Duration(hours=1)),
                    (datetime.timedelta(seconds=5400), Duration(hours=1, minutes=30)),
                    (datetime.timedelta(seconds=7200), Duration(hours=2)),
                    (datetime.timedelta(seconds=10800), Duration(hours=3)),
                ],
                default="60 minutes",
                help_text="default duration",
            ),
        ),
    ]
