# Generated by Django 6.0.3 on 2026-03-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeleteAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("no_inter", "No interested"),
                            ("no_use", "Interested but not using it"),
                            ("no_reason", "No reasons"),
                            ("privacy", "Worried for my privacy"),
                            ("no_fit", "Theory does not fit me"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("confirm", models.BooleanField()),
            ],
        ),
    ]
