# Generated by Django 6.0.3 on 2026-03-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_deleteaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deleteaccount",
            name="reason",
            field=models.CharField(
                choices=[
                    ("no_inter", "No interested"),
                    ("no_use", "Interested but not using it"),
                    ("no_reason", "No reasons"),
                    ("privacy", "Worried for my privacy"),
                    ("no_fit", "Style does not fit me"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
