# Generated by Django 6.0.3 on 2026-03-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_page_created_page_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
