# Generated by Django 6.0 on 2026-01-29 10:42

import datetime
from pendulum import Time
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomCalendarModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="", max_length=20)),
                ("description", models.CharField(default="", max_length=200)),
                ("percentage", models.IntegerField(default=0)),
                ("cost", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "room calendar",
                "verbose_name_plural": "room calendars",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TenantModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("display_name", models.CharField(max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "agreement",
                    models.CharField(
                        choices=[
                            ("Amount", "By Amount"),
                            ("Percentage", "By Percentage"),
                            ("Block", "By Block"),
                        ],
                        default="Amount",
                        max_length=10,
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="room_calendar_app.roomcalendarmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tenant",
                "verbose_name_plural": "tenants",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="BlocksModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Mon"),
                            (1, "Tue"),
                            (2, "Wed"),
                            (3, "Thu"),
                            (4, "Fri"),
                            (5, "Sat"),
                            (6, "Sun"),
                        ]
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        choices=[
                            (Time(8, 0, 0), "08:00 AM"),
                            (Time(8, 30, 0), "08:30 AM"),
                            (Time(9, 0, 0), "09:00 AM"),
                            (Time(9, 30, 0), "09:30 AM"),
                            (Time(10, 0, 0), "10:00 AM"),
                            (Time(10, 30, 0), "10:30 AM"),
                            (Time(11, 0, 0), "11:00 AM"),
                            (Time(11, 30, 0), "11:30 AM"),
                            (Time(12, 0, 0), "12:00 PM"),
                            (Time(12, 30, 0), "12:30 PM"),
                            (Time(13, 0, 0), "01:00 PM"),
                            (Time(13, 30, 0), "01:30 PM"),
                            (Time(14, 0, 0), "02:00 PM"),
                            (Time(14, 30, 0), "02:30 PM"),
                            (Time(15, 0, 0), "03:00 PM"),
                            (Time(15, 30, 0), "03:30 PM"),
                            (Time(16, 0, 0), "04:00 PM"),
                            (Time(16, 30, 0), "04:30 PM"),
                            (Time(17, 0, 0), "05:00 PM"),
                            (Time(17, 30, 0), "05:30 PM"),
                            (Time(18, 0, 0), "06:00 PM"),
                            (Time(18, 30, 0), "06:30 PM"),
                            (Time(19, 0, 0), "07:00 PM"),
                            (Time(19, 30, 0), "07:30 PM"),
                            (Time(20, 0, 0), "08:00 PM"),
                            (Time(20, 30, 0), "08:30 PM"),
                            (Time(21, 0, 0), "09:00 PM"),
                            (Time(21, 30, 0), "09:30 PM"),
                            (Time(22, 0, 0), "10:00 PM"),
                        ]
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        choices=[
                            (Time(8, 0, 0), "08:00 AM"),
                            (Time(8, 30, 0), "08:30 AM"),
                            (Time(9, 0, 0), "09:00 AM"),
                            (Time(9, 30, 0), "09:30 AM"),
                            (Time(10, 0, 0), "10:00 AM"),
                            (Time(10, 30, 0), "10:30 AM"),
                            (Time(11, 0, 0), "11:00 AM"),
                            (Time(11, 30, 0), "11:30 AM"),
                            (Time(12, 0, 0), "12:00 PM"),
                            (Time(12, 30, 0), "12:30 PM"),
                            (Time(13, 0, 0), "01:00 PM"),
                            (Time(13, 30, 0), "01:30 PM"),
                            (Time(14, 0, 0), "02:00 PM"),
                            (Time(14, 30, 0), "02:30 PM"),
                            (Time(15, 0, 0), "03:00 PM"),
                            (Time(15, 30, 0), "03:30 PM"),
                            (Time(16, 0, 0), "04:00 PM"),
                            (Time(16, 30, 0), "04:30 PM"),
                            (Time(17, 0, 0), "05:00 PM"),
                            (Time(17, 30, 0), "05:30 PM"),
                            (Time(18, 0, 0), "06:00 PM"),
                            (Time(18, 30, 0), "06:30 PM"),
                            (Time(19, 0, 0), "07:00 PM"),
                            (Time(19, 30, 0), "07:30 PM"),
                            (Time(20, 0, 0), "08:00 PM"),
                            (Time(20, 30, 0), "08:30 PM"),
                            (Time(21, 0, 0), "09:00 PM"),
                            (Time(21, 30, 0), "09:30 PM"),
                            (Time(22, 0, 0), "10:00 PM"),
                        ]
                    ),
                ),
                (
                    "monthly_cost",
                    models.IntegerField(
                        blank=True, default=0, help_text="Monthly cost for this block"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Select a linked tenant",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="room_calendar_app.tenantmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "block",
                "verbose_name_plural": "blocks",
                "ordering": ("day", "start_time"),
            },
        ),
    ]
