# Generated by Django 6.0a1 on 2025-10-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomcalendarmodel",
            name="cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="roomcalendarmodel",
            name="percentage",
            field=models.IntegerField(default=0),
        ),
    ]
