# Generated by Django 6.0a1 on 2025-12-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blocksmodel",
            name="monthly_cost",
            field=models.IntegerField(
                blank=True, default=0, help_text="Monthly cost for this block"
            ),
        ),
    ]
