# Generated by Django 5.2.1 on 2025-05-22 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occurrencemodel",
            name="event",
        ),
        migrations.RemoveField(
            model_name="occurrencemodel",
            name="calendar",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="OccurrenceModel",
        ),
    ]
