# Generated by Django 6.0a1 on 2025-12-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0002_blocksmodel_monthly_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantmodel",
            name="agreement",
            field=models.CharField(
                choices=[
                    ("Amount", "Amount"),
                    ("Percentage", "Percentage"),
                    ("Block", "Block"),
                ],
                default="Amount",
                max_length=10,
            ),
        ),
    ]
