# Generated by Django 6.0a1 on 2025-11-14 17:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0002_alter_tenantmodel_calendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlocksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (6, "Sun"),
                            (0, "Mon"),
                            (1, "Tue"),
                            (2, "Wed"),
                            (3, "Thu"),
                            (4, "Fri"),
                            (5, "Sat"),
                        ]
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        choices=[
                            (datetime.timedelta(seconds=1800), "0:30:00"),
                            (datetime.timedelta(seconds=3600), "1:00:00"),
                            (datetime.timedelta(seconds=5400), "1:30:00"),
                            (datetime.timedelta(seconds=7200), "2:00:00"),
                            (datetime.timedelta(seconds=10800), "3:00:00"),
                        ]
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        choices=[
                            (datetime.timedelta(seconds=1800), "0:30:00"),
                            (datetime.timedelta(seconds=3600), "1:00:00"),
                            (datetime.timedelta(seconds=5400), "1:30:00"),
                            (datetime.timedelta(seconds=7200), "2:00:00"),
                            (datetime.timedelta(seconds=10800), "3:00:00"),
                        ]
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="room_calendar_app.tenantmodel",
                    ),
                ),
            ],
        ),
    ]
