# Generated by Django 6.0 on 2026-02-02 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("session_client", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("quarter", "quarter"),
                            ("year", "year"),
                            ("tax_year", "tax_year"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "quarter",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            ("1", "first quarter"),
                            ("2", "second quarter"),
                            ("3", "third quarter"),
                            ("4", "fourth quarter"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "tax_year_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("jan-dec", "January(1)-December(31)"),
                            ("apr-apr", "April(6)-April(5)"),
                            ("apr-mar", "April(1)-March(31)"),
                            ("jul-jun", "July(1)-June(30)"),
                            ("mar-mar", "March(21)-March(20)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("year_start", models.IntegerField(blank=True, default=2026)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_year",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("jan-dec", "January(1)-December(31)"),
                            ("apr-apr", "April(6)-April(5)"),
                            ("apr-mar", "April(1)-March(31)"),
                            ("jul-jun", "July(1)-June(30)"),
                            ("mar-mar", "March(21)-March(20)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=60.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_income",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_recurrent",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("report", models.ManyToManyField(to="my_numbers.reportmodel")),
                (
                    "session",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="session_client.sessionmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
