# Generated by Django 6.0a1 on 2025-12-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_numbers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionmodel",
            old_name="fee",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="income",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
