# Generated by Django 6.0a1 on 2025-12-22 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_numbers", "0003_transactionmodel_recurrent_reportmodel_and_more"),
        ("session_client", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactionmodel",
            old_name="income",
            new_name="is_income",
        ),
        migrations.RenameField(
            model_name="transactionmodel",
            old_name="recurrent",
            new_name="is_recurrent",
        ),
        migrations.AddField(
            model_name="reportmodel",
            name="quarter",
            field=models.IntegerField(
                blank=True,
                choices=[
                    ("1", "first quarter"),
                    ("2", "second quarter"),
                    ("3", "third quarter"),
                    ("4", "fourth quarter"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transactionmodel",
            name="session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="session_client.sessionmodel",
            ),
        ),
        migrations.AlterField(
            model_name="reportmodel",
            name="period_type",
            field=models.CharField(
                choices=[
                    ("quarter", "quarter"),
                    ("year", "year"),
                    ("tax_year", "tax_year"),
                ],
                max_length=15,
            ),
        ),
    ]
