# Generated by Django 6.0a1 on 2025-12-22 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_numbers", "0004_rename_income_transactionmodel_is_income_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reportmodel",
            name="tax_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("jan-dec", "January(1)-December(31)"),
                    ("apr-apr", "April(6)-April(5)"),
                    ("apr-mar", "April(1)-March(31)"),
                    ("jul-jun", "July(1)-June(30)"),
                    ("mar-mar", "March(21)-March(20)"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="reportmodel",
            name="quarter",
            field=models.IntegerField(
                blank=True,
                choices=[
                    ("1", "first quarter"),
                    ("2", "second quarter"),
                    ("3", "third quarter"),
                    ("4", "fourth quarter"),
                ],
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ReportSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_year",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("jan-dec", "January(1)-December(31)"),
                            ("apr-apr", "April(6)-April(5)"),
                            ("apr-mar", "April(1)-March(31)"),
                            ("jul-jun", "July(1)-June(30)"),
                            ("mar-mar", "March(21)-March(20)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
