# Generated by Django 6.0a1 on 2025-12-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_numbers", "0005_reportmodel_tax_year_alter_reportmodel_quarter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportmodel",
            name="year_start",
            field=models.IntegerField(blank=True, default=2025),
        ),
    ]
