# Generated by Django 5.1.6 on 2025-04-02 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="active",
            field=models.BooleanField(
                default=True, help_text="Mark if its a current client"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="code",
            field=models.CharField(
                default="", help_text="Add an Identifier code", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="fee",
            field=models.IntegerField(
                default=50,
                help_text="Whats your agreed fee",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="goal",
            field=models.TextField(
                blank=True, default="", help_text="What's the original goal for therapy"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="motive",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Add client's reason for consulting",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="nick_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Give it a memorable nickname",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="rel",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Write a note about your client's relational context",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="strategy",
            field=models.TextField(
                blank=True, default="", help_text="Your first idea on how to work"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="type",
            field=models.CharField(
                choices=[
                    ("Pvt", "Private"),
                    ("Srv", "Service"),
                    ("EAP", "EAP"),
                    ("Sp", "Supervisee"),
                    ("Other", "Other"),
                ],
                default="Pvt",
                help_text="Select a type of client",
                max_length=20,
            ),
        ),
    ]
