# Generated by Django 5.1.6 on 2025-04-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0002_alter_client_active_alter_client_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="active",
        ),
        migrations.RemoveField(
            model_name="client",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="client",
            name="motive",
        ),
        migrations.RemoveField(
            model_name="client",
            name="rel",
        ),
        migrations.RemoveField(
            model_name="client",
            name="strategy",
        ),
        migrations.AlterField(
            model_name="client",
            name="code",
            field=models.CharField(help_text="Add an Identifier code", max_length=10),
        ),
    ]
