# Generated by Django 5.1.6 on 2025-04-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0005_client_archived_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="open",
            field=models.BooleanField(default=True),
        ),
    ]
