# Generated by Django 6.0 on 2026-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IndexPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("landing", models.TextField()),
                ("feature_title", models.CharField(max_length=200)),
                ("feature_content", models.TextField()),
                ("feature_image", models.ImageField(upload_to="images/")),
                ("feature_title_2", models.CharField(max_length=200)),
                ("feature_content_2", models.TextField()),
                ("feature_image_2", models.ImageField(upload_to="images/")),
                ("feature_title_3", models.CharField(max_length=200)),
                ("feature_content_3", models.TextField()),
                ("feature_image_3", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
