# Generated by Django 5.1.3 on 2024-12-03 11:42

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=100)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("client", "Client Session"),
                            ("super", "Supervision"),
                            ("Admin", "Admin"),
                            ("Processing", "Processing"),
                            ("CPD", "CPD"),
                        ],
                        max_length=20,
                        verbose_name="event type",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tools.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
                "ordering": ("title", "event_type"),
            },
        ),
        migrations.CreateModel(
            name="MultiOccurrenceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_start", models.DateField(auto_now=True)),
                (
                    "start_time",
                    models.IntegerField(
                        choices=[
                            ("08:00:00", "08:00 AM"),
                            ("08:15:00", "08:15 AM"),
                            ("08:30:00", "08:30 AM"),
                            ("08:45:00", "08:45 AM"),
                            ("09:00:00", "09:00 AM"),
                            ("09:15:00", "09:15 AM"),
                            ("09:30:00", "09:30 AM"),
                            ("09:45:00", "09:45 AM"),
                            ("10:00:00", "10:00 AM"),
                            ("10:15:00", "10:15 AM"),
                            ("10:30:00", "10:30 AM"),
                            ("10:45:00", "10:45 AM"),
                            ("11:00:00", "11:00 AM"),
                            ("11:15:00", "11:15 AM"),
                            ("11:30:00", "11:30 AM"),
                            ("11:45:00", "11:45 AM"),
                            ("12:00:00", "12:00 PM"),
                            ("12:15:00", "12:15 PM"),
                            ("12:30:00", "12:30 PM"),
                            ("12:45:00", "12:45 PM"),
                            ("13:00:00", "01:00 PM"),
                            ("13:15:00", "01:15 PM"),
                            ("13:30:00", "01:30 PM"),
                            ("13:45:00", "01:45 PM"),
                            ("14:00:00", "02:00 PM"),
                            ("14:15:00", "02:15 PM"),
                            ("14:30:00", "02:30 PM"),
                            ("14:45:00", "02:45 PM"),
                            ("15:00:00", "03:00 PM"),
                            ("15:15:00", "03:15 PM"),
                            ("15:30:00", "03:30 PM"),
                            ("15:45:00", "03:45 PM"),
                            ("16:00:00", "04:00 PM"),
                            ("16:15:00", "04:15 PM"),
                            ("16:30:00", "04:30 PM"),
                            ("16:45:00", "04:45 PM"),
                            ("17:00:00", "05:00 PM"),
                            ("17:15:00", "05:15 PM"),
                            ("17:30:00", "05:30 PM"),
                            ("17:45:00", "05:45 PM"),
                            ("18:00:00", "06:00 PM"),
                            ("18:15:00", "06:15 PM"),
                            ("18:30:00", "06:30 PM"),
                            ("18:45:00", "06:45 PM"),
                            ("19:00:00", "07:00 PM"),
                            ("19:15:00", "07:15 PM"),
                            ("19:30:00", "07:30 PM"),
                            ("19:45:00", "07:45 PM"),
                            ("20:00:00", "08:00 PM"),
                            ("20:15:00", "08:15 PM"),
                            ("20:30:00", "08:30 PM"),
                            ("20:45:00", "08:45 PM"),
                            ("21:00:00", "09:00 PM"),
                        ]
                    ),
                ),
                (
                    "end_time",
                    models.IntegerField(
                        choices=[
                            ("08:00:00", "08:00 AM"),
                            ("08:15:00", "08:15 AM"),
                            ("08:30:00", "08:30 AM"),
                            ("08:45:00", "08:45 AM"),
                            ("09:00:00", "09:00 AM"),
                            ("09:15:00", "09:15 AM"),
                            ("09:30:00", "09:30 AM"),
                            ("09:45:00", "09:45 AM"),
                            ("10:00:00", "10:00 AM"),
                            ("10:15:00", "10:15 AM"),
                            ("10:30:00", "10:30 AM"),
                            ("10:45:00", "10:45 AM"),
                            ("11:00:00", "11:00 AM"),
                            ("11:15:00", "11:15 AM"),
                            ("11:30:00", "11:30 AM"),
                            ("11:45:00", "11:45 AM"),
                            ("12:00:00", "12:00 PM"),
                            ("12:15:00", "12:15 PM"),
                            ("12:30:00", "12:30 PM"),
                            ("12:45:00", "12:45 PM"),
                            ("13:00:00", "01:00 PM"),
                            ("13:15:00", "01:15 PM"),
                            ("13:30:00", "01:30 PM"),
                            ("13:45:00", "01:45 PM"),
                            ("14:00:00", "02:00 PM"),
                            ("14:15:00", "02:15 PM"),
                            ("14:30:00", "02:30 PM"),
                            ("14:45:00", "02:45 PM"),
                            ("15:00:00", "03:00 PM"),
                            ("15:15:00", "03:15 PM"),
                            ("15:30:00", "03:30 PM"),
                            ("15:45:00", "03:45 PM"),
                            ("16:00:00", "04:00 PM"),
                            ("16:15:00", "04:15 PM"),
                            ("16:30:00", "04:30 PM"),
                            ("16:45:00", "04:45 PM"),
                            ("17:00:00", "05:00 PM"),
                            ("17:15:00", "05:15 PM"),
                            ("17:30:00", "05:30 PM"),
                            ("17:45:00", "05:45 PM"),
                            ("18:00:00", "06:00 PM"),
                            ("18:15:00", "06:15 PM"),
                            ("18:30:00", "06:30 PM"),
                            ("18:45:00", "06:45 PM"),
                            ("19:00:00", "07:00 PM"),
                            ("19:15:00", "07:15 PM"),
                            ("19:30:00", "07:30 PM"),
                            ("19:45:00", "07:45 PM"),
                            ("20:00:00", "08:00 PM"),
                            ("20:15:00", "08:15 PM"),
                            ("20:30:00", "08:30 PM"),
                            ("20:45:00", "08:45 PM"),
                            ("21:00:00", "09:00 PM"),
                        ]
                    ),
                ),
                ("until", models.DateField(blank=True, default=datetime.date.today)),
                (
                    "frequency",
                    models.IntegerField(
                        choices=[
                            (3, "Day(s)"),
                            (2, "Week(s)"),
                            (1, "Month(s)"),
                            (0, "Year(s)"),
                        ],
                        default=2,
                    ),
                ),
                ("interval", models.IntegerField(blank=True, default=1)),
                (
                    "week_days_1",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (7, "Sun"),
                            (1, "Mon"),
                            (2, "Tue"),
                            (3, "Wed"),
                            (4, "Thu"),
                            (5, "Fri"),
                            (6, "Sat"),
                        ],
                    ),
                ),
                (
                    "week_days_2",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (7, "Sun"),
                            (1, "Mon"),
                            (2, "Tue"),
                            (3, "Wed"),
                            (4, "Thu"),
                            (5, "Fri"),
                            (6, "Sat"),
                        ],
                    ),
                ),
                (
                    "week_days_3",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (7, "Sun"),
                            (1, "Mon"),
                            (2, "Tue"),
                            (3, "Wed"),
                            (4, "Thu"),
                            (5, "Fri"),
                            (6, "Sat"),
                        ],
                    ),
                ),
                (
                    "month_option",
                    models.CharField(
                        choices=[("on", "On the"), ("each", "Each:")],
                        default="each",
                        max_length=20,
                    ),
                ),
                (
                    "month_ordinal",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "first"),
                            (2, "second"),
                            (3, "third"),
                            (4, "fourth"),
                            (-1, "last"),
                        ],
                    ),
                ),
                (
                    "month_ordinal_day",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (7, "Sunday"),
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                        ],
                    ),
                ),
                ("each_month_day", models.IntegerField(blank=True, default=1)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="room_calendar_app.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OccurrenceModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="start time")),
                ("end_time", models.DateTimeField(verbose_name="end time")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="room_calendar_app.event",
                        verbose_name="event",
                    ),
                ),
                (
                    "multi_occurrence_model",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="room_calendar_app.multioccurrencemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "occurrence",
                "verbose_name_plural": "occurrences",
                "ordering": ("start_time", "end_time"),
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="RoomCalendarModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(default="", max_length=20)),
                ("description", models.CharField(default="", max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "room calendar",
                "verbose_name_plural": "room calendars",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="event",
            name="room_calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="room_calendar_app.roomcalendarmodel",
            ),
        ),
        migrations.CreateModel(
            name="TenantModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "tenant",
                "verbose_name_plural": "tenants",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="roomcalendarmodel",
            name="tenants",
            field=models.ManyToManyField(
                related_query_name="tenants", to="room_calendar_app.tenantmodel"
            ),
        ),
    ]
