# Generated by Django 5.1.6 on 2025-02-12 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="occurrencemodel",
            name="multi_occurrence_model",
        ),
        migrations.DeleteModel(
            name="MultiOccurrenceModel",
        ),
    ]
