# Generated by Django 5.1.3 on 2024-12-04 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="room_calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="room_calendar_app.roomcalendarmodel",
            ),
        ),
        migrations.AlterField(
            model_name="multioccurrencemodel",
            name="day_start",
            field=models.DateField(),
        ),
    ]
