# Generated by Django 5.1.6 on 2025-03-15 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "room_calendar_app",
            "0002_remove_occurrencemodel_multi_occurrence_model_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencemodel",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="room_calendar_app.roomcalendarmodel",
            ),
        ),
        migrations.AlterField(
            model_name="occurrencemodel",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="room_calendar_app.event",
            ),
        ),
    ]
