# Generated by Django 5.1.3 on 2024-12-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0002_event_user_alter_event_room_calendar_and_more"),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tools.client",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="room_calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="room_calendar_app.roomcalendarmodel",
            ),
        ),
    ]
