# Generated by Django 5.1.6 on 2025-03-15 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "room_calendar_app",
            "0003_occurrencemodel_calendar_alter_occurrencemodel_event",
        ),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tools.client",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="room_calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="room_calendar_app.roomcalendarmodel",
            ),
        ),
    ]
