# Generated by Django 5.1.3 on 2024-12-10 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0004_event_created_at_event_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ("updated_at", "title"),
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.AlterModelOptions(
            name="occurrencemodel",
            options={
                "base_manager_name": "objects",
                "ordering": ("start_time",),
                "verbose_name": "occurrence",
                "verbose_name_plural": "occurrences",
            },
        ),
        migrations.RemoveField(
            model_name="occurrencemodel",
            name="end_time",
        ),
        migrations.AddField(
            model_name="occurrencemodel",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (30, "30 min"),
                    (60, "1 hour"),
                    (90, "1.5 hours"),
                    (120, "2 hours"),
                ],
                default=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="occurrencemodel",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="room_calendar_app.event",
            ),
        ),
        migrations.AlterField(
            model_name="occurrencemodel",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="occurrencemodel",
            name="multi_occurrence_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="room_calendar_app.multioccurrencemodel",
            ),
        ),
        migrations.AlterField(
            model_name="occurrencemodel",
            name="start_time",
            field=models.DateTimeField(unique=True),
        ),
    ]
