# Generated by Django 5.1.6 on 2025-03-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0004_alter_event_client_alter_event_room_calendar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
