# Generated by Django 5.1.3 on 2024-12-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "room_calendar_app",
            "0005_alter_event_options_alter_occurrencemodel_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencemodel",
            name="duration",
            field=models.DurationField(
                choices=[
                    (30, "30 min"),
                    (60, "1 hour"),
                    (90, "1.5 hours"),
                    (120, "2 hours"),
                ]
            ),
        ),
    ]
