# Generated by Django 5.1.3 on 2025-01-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0006_alter_occurrencemodel_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrencemodel",
            name="duration",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="occurrencemodel",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
