# Generated by Django 5.1.3 on 2025-01-16 20:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0007_alter_occurrencemodel_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occurrencemodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
