# Generated by Django 6.0 on 2026-02-12 13:59

from pendulum import Time
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0001_initial"),
        ("session_client", "0003_remove_sessionmodel_calendar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmodel",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Override Client's tenant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="room_calendar_app.tenantmodel",
            ),
        ),
        migrations.CreateModel(
            name="ClientExtraTimes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Mon"),
                            (1, "Tue"),
                            (2, "Wed"),
                            (3, "Thu"),
                            (4, "Fri"),
                            (5, "Sat"),
                            (6, "Sun"),
                        ],
                        default=1,
                        help_text="Day of Week",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        choices=[
                            (Time(8, 0, 0), "08:00 AM"),
                            (Time(8, 30, 0), "08:30 AM"),
                            (Time(9, 0, 0), "09:00 AM"),
                            (Time(9, 30, 0), "09:30 AM"),
                            (Time(10, 0, 0), "10:00 AM"),
                            (Time(10, 30, 0), "10:30 AM"),
                            (Time(11, 0, 0), "11:00 AM"),
                            (Time(11, 30, 0), "11:30 AM"),
                            (Time(12, 0, 0), "12:00 PM"),
                            (Time(12, 30, 0), "12:30 PM"),
                            (Time(13, 0, 0), "01:00 PM"),
                            (Time(13, 30, 0), "01:30 PM"),
                            (Time(14, 0, 0), "02:00 PM"),
                            (Time(14, 30, 0), "02:30 PM"),
                            (Time(15, 0, 0), "03:00 PM"),
                            (Time(15, 30, 0), "03:30 PM"),
                            (Time(16, 0, 0), "04:00 PM"),
                            (Time(16, 30, 0), "04:30 PM"),
                            (Time(17, 0, 0), "05:00 PM"),
                            (Time(17, 30, 0), "05:30 PM"),
                            (Time(18, 0, 0), "06:00 PM"),
                            (Time(18, 30, 0), "06:30 PM"),
                            (Time(19, 0, 0), "07:00 PM"),
                            (Time(19, 30, 0), "07:30 PM"),
                            (Time(20, 0, 0), "08:00 PM"),
                            (Time(20, 30, 0), "08:30 PM"),
                            (Time(21, 0, 0), "09:00 PM"),
                            (Time(21, 30, 0), "09:30 PM"),
                            (Time(22, 0, 0), "10:00 PM"),
                        ],
                        help_text="Time of Session",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="session_client.clientmodel",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set different tenant",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="room_calendar_app.tenantmodel",
                    ),
                ),
            ],
        ),
    ]
