# Generated by Django 6.0 on 2026-02-22 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0001_initial"),
        ("session_client", "0006_clienttimes_created_at_alter_clienttimes_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientmodel",
            name="day",
        ),
        migrations.RemoveField(
            model_name="clientmodel",
            name="time",
        ),
        migrations.AlterField(
            model_name="clientmodel",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="default tenant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="room_calendar_app.tenantmodel",
            ),
        ),
    ]
