# Generated by Django 6.0.3 on 2026-03-18 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room_calendar_app", "0002_alter_tenantmodel_calendar"),
        ("session_client", "0008_clienttimes_fortnight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clienttimes",
            name="tenant",
            field=models.ForeignKey(
                help_text="Set tenant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="room_calendar_app.tenantmodel",
            ),
        ),
    ]
