# Generated by Django 6.0.3 on 2026-04-24 20:43

import pendulum.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0009_alter_clienttimes_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmodel",
            name="date",
            field=models.DateField(
                default=pendulum.DateTime.date, help_text="Date of session"
            ),
        ),
    ]
