# Generated by Django 6.0.3 on 2026-05-04 12:44

from pendulum import Duration
import pendulum.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0010_alter_sessionmodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmodel",
            name="duration",
            field=models.DurationField(
                choices=[
                    (1800, Duration(minutes=30)),
                    (3600, Duration(hours=1)),
                    (5400, Duration(hours=1, minutes=30)),
                    (7200, Duration(hours=2)),
                    (10800, Duration(hours=3)),
                ],
                default="60 minutes",
                help_text="default duration",
            ),
        ),
        migrations.AlterField(
            model_name="sessionmodel",
            name="date",
            field=models.DateField(
                default=pendulum.now().date(), help_text="Date of session"
            ),
        ),
    ]
