# Generated by Django 6.0.3 on 2026-05-04 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0014_alter_clientmodel_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmodel",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 5, 4, 14, 47, 28, 513053, tzinfo=datetime.timezone.utc
                ),
                help_text="Date of session",
            ),
        ),
    ]
