# Generated by Django 6.0.3 on 2026-05-20 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0016_alter_sessionmodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmodel",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 5, 20, 20, 23, 4, 666393, tzinfo=datetime.timezone.utc
                ),
                help_text="Date of session",
            ),
        ),
    ]
