# Generated by Django 6.0.3 on 2026-05-27 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("session_client", "0018_alter_sessionmodel_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionmodel",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 5, 27, 19, 30, 52, 696559, tzinfo=datetime.timezone.utc
                ),
                help_text="Date of session",
            ),
        ),
    ]
